-- phpMyAdmin SQL Dump
-- version 4.6.4
-- https://www.phpmyadmin.net/
--
-- Client :  127.0.0.1
-- Généré le :  Jeu 16 Mars 2017 à 09:16
-- Version du serveur :  5.7.14
-- Version de PHP :  5.6.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `movie_journey_bdd`
--

-- --------------------------------------------------------

--
-- Structure de la table `movie`
--

CREATE TABLE `movie` (
  `id` int(10) NOT NULL,
  `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `backdrop_path` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(2000) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Contenu de la table `movie`
--

INSERT INTO `movie` (`id`, `name`, `backdrop_path`, `description`) VALUES
(1, 'Inception', 'https://image.tmdb.org/t/p/w640/d5AfeWE8Ozk5QSbjB7rF3GN2d76.jpg', 'Dom Cobb est un voleur expérimenté, le meilleur dans l\'art dangereux de l\'extraction, voler les secrets les plus intimes enfouis au plus profond du subconscient durant une phase de rêve, lorsque l\'esprit est le plus vulnérable. Les capacités de Cobb ont fait des envieux dans le monde tourmenté de l\'espionnage industriel alors qu\'il devient fugitif en perdant tout ce qu\'il a un jour aimé. Une chance de se racheter lui est alors offerte. Une ultime mission grâce à laquelle il pourrait retrouver sa vie passée mais uniquement s\'il parvient à accomplir l\'impossible inception.'),
(2, 'Indiana Jones et la dernière croisade', 'https://image.tmdb.org/t/p/w640/ftdvraBCzt0XiAxIyDwbXu8BgVr.jpg', 'Indiana Jones se lance cette fois-ci à la recherche du Saint Graal, accompagné de l\'éminent et très maladroit Dr Henry Jones, son père. Malheureusement, ils ne sont pas les seuls lancés sur la trace du trésor, les nazis le convoitent également.'),
(3, 'Skyfall', 'https://image.tmdb.org/t/p/w640/ciO7oM6wXLEBTU2VavHJQzAsOCb.jpg', 'Lorsque la dernière mission de Bond tourne mal, plusieurs agents infiltrés se retrouvent exposés dans le monde entier. Le MI6 est attaqué, et M est obligée de relocaliser l’Agence. Ces événements ébranlent son autorité, et elle est remise en cause par Mallory, le nouveau président de l’ISC, le comité chargé du renseignement et de la sécurité. Le MI6 est à présent sous le coup d’une double menace, intérieure et extérieure. Il ne reste à M qu’un seul allié de confiance vers qui se tourner : Bond. Plus que jamais, 007 va devoir agir dans l’ombre. Avec l’aide d’Ève, un agent de terrain, il se lance sur la piste du mystérieux Silva, dont il doit identifier coûte que coûte l’objectif secret et mortel.'),
(4, 'Rosemary s Baby', 'https://image.tmdb.org/t/p/w640/xbTIMRk36qthU4RDRBYoBVbhQbZ.jpg', 'Malgré les conseils de leur vieil ami Hutch, Guy Woodhouse et sa jeune femme, enceinte, s\'installent dans un immeuble new-yorkais vétuste, considéré par leur ami comme une demeure maléfique. Aussitôt, leurs voisins, Minnie et Roman Castevet, vieux couple d\'Europe centrale, imposent leur amitié et leurs services. Si Guy accepte facilement ce voisinage, Rosemary s\'en inquiète...'),
(5, 'Bridget Jones s Baby', 'https://image.tmdb.org/t/p/w640/q8ZYuvRF1fA3TeKlpv2VQMa6vyC.jpg', 'Après avoir rompu avec Mark Darcy, Bridget se retrouve de nouveau célibataire, 40 ans passés, plus concentrée sur sa carrière et ses amis que sur sa vie amoureuse. Pour une fois, tout est sous contrôle ! Jusqu’à ce que Bridget fasse la rencontre de Jack… Puis retrouve Darcy… Puis découvre qu’elle est enceinte… Mais de qui ???'),
(6, 'Les visiteurs 3', 'https://image.tmdb.org/t/p/w640/c74GF2DdV3L2R7z1MmwD0nzRS0E.jpg', 'Bloqués dans les couloirs du temps, Godefroy de Montmirail et son fidèle serviteur Jacquouille sont projetés dans une époque de profonds bouleversements politiques et sociaux : la Révolution Française... Plus précisément, La Terreur, période de grands dangers pendant laquelle les descendants de Jacquouille La Fripouille, révolutionnaires convaincus, confisquent le château et tous les biens des descendants de Godefroy de Montmirail, aristocrates arrogants en fuite dont la vie ne tient qu\'à un fil.\r\n'),
(7, 'Les visiteurs 2 ', 'https://image.tmdb.org/t/p/w640/abhPJOJ6z7T4dkXFA2M573gjsXy.jpg', 'Un coup de théâtre interrompt les préparatifs du mariage de Godefroy de Montmirail et de Frénégonde de Pouille. On vient de dérober au duc, le père de Frénégonde, la dentelette de Sainte-Rolande, relique sacrée qui assure fécondité aux femmes de la famille de Pouille ainsi que tous ses bijoux. Ce sont Jacquouille et Ginette qui ont fait ce larcin et sont partis dans le présent. Il ne reste plus qu\'une solution à Godefroy s\'il veut réaliser son mariage et assurer sa descendance : repartir dans le présent, récupérer les bijoux, la dentelette et Jacquouille la fripouille.\r\n'),
(8, 'Maman j ai raté l avion', 'https://image.tmdb.org/t/p/w640/rsw3RJBBIPieJpAtZTc0jbcZFo6.jpg', 'La famille McCallister a décidé de passer les fêtes de Noël à Paris. Seulement Kate et Peter McCallister s\'aperçoivent dans l\'avion qu\'il leur manque le plus jeune de leurs enfants, Kevin, âgé de 9 ans. D\'abord désespéré, Kevin reprend vite les choses en main et s\'organise pour vivre le mieux possible. Quand deux cambrioleurs choisissent sa maison pour commettre leurs méfaits.'),
(9, 'Django Unchained', 'https://image.tmdb.org/t/p/w640/iWXGPkf8TwRuXecfDs0j3dDBNLA.jpg', 'Dans le sud des États-Unis, deux ans avant la guerre de Sécession, le Dr King Schultz, un chasseur de primes allemand, fait l’acquisition de Django, un esclave qui peut l’aider à traquer les frères Brittle, les meurtriers qu’il recherche. Schultz promet à Django de lui rendre sa liberté lorsqu’il aura capturé les Brittle – morts ou vifs. Alors que les deux hommes pistent les dangereux criminels, Django n’oublie pas que son seul but est de retrouver Broomhilda, sa femme, dont il fut séparé à cause du commerce des esclaves… Lorsque Django et Schultz arrivent dans l’immense plantation du puissant Calvin Candie, ils éveillent les soupçons de Stephen, un esclave qui sert Candie et a toute sa confiance. Le moindre de leurs mouvements est désormais épié par une dangereuse organisation de plus en plus proche… Si Django et Schultz veulent espérer s’enfuir avec Broomhilda, ils vont devoir choisir entre l’indépendance et la solidarité, entre le sacrifice et la survie…'),
(10, 'L Évadé d Alcatraz', 'https://image.tmdb.org/t/p/w640/vWK4VG2FlFAJmo2gD1R3f11c7IZ.jpg', 'Frank Lee Morris est devenu un spécialiste des tentatives d\'évasion. Pour le calmer définitivement, on le transfère à la célèbre prison d\'Alcatraz. A peine arrivé sur le rocher, Frank gamberge déjà. Au fil des jours, il organise dans les moindres détails sa future évasion. Il se lie d\'amitié avec plusieurs détenus, dont les frères Anglin, de vieilles connaissances, et un certain Charly Butts. Tous sont marqués par le calme et la lucidité de leur nouveau compagnon. Le jour venu, Frank expose son projet à ses codétenus et les persuade de tenter l\'aventure avec lui. Chacun devra minutieusement accomplir la tâche impartie par Frank. A l\'aide d\'une pince à ongles et d\'une cuillère, Frank commence ses premiers travaux...'),
(11, 'Star Wars IV', 'https://image.tmdb.org/t/p/w640/yVaQ34IvVDAZAWxScNdeIkaepDq.jpg', 'Il y a bien longtemps, dans une galaxie très lointaine... La guerre civile fait rage entre l\'Empire galactique et l\'Alliance rebelle. Capturée par les troupes de choc de l\'Empereur menées par le sombre et impitoyable Dark Vador, la princesse Leia Organa dissimule les plans de l’Étoile Noire, une station spatiale invulnérable, à son droïde R2-D2 avec pour mission de les remettre au Jedi Obi-Wan Kenobi. Accompagné de son fidèle compagnon, le droïde de protocole C-3PO, R2-D2 s\'échoue sur la planète Tatooine et termine sa quête chez le jeune Luke Skywalker. Rêvant de devenir pilote mais confiné aux travaux de la ferme, ce dernier se lance à la recherche de ce mystérieux Obi-Wan Kenobi, devenu ermite au cœur des montagnes désertiques de Tatooine...'),
(12, 'Pretty woman', 'https://image.tmdb.org/t/p/w640/9sSUMrlSQ2rquEfIDHBonxtfRoV.jpg', 'Quand Edward Lewis, businessman de talent, s’offre les services de la belle Vivian, beauté fatale qui arpente chaque nuit les trottoirs d’Hollywood Boulevard, il décide par amusement de l’engager, de lui faire découvrir son style de vie, de la couvrir de cadeaux. Ils vivent ainsi quelque temps, jusqu’au jour où ils découvrent tous deux qu’ils ne peuvent plus se séparer...'),
(13, 'La nuit au musée', 'https://image.tmdb.org/t/p/w640/aQbH459SMQMu62STrRFtcPgPRCq.jpg', 'Le Muséum d\'Histoire Naturelle renferme dans ses murs un secret mystérieux et stupéfiant que Larry, nouveau gardien de sécurité, ne va pas tarder à découvrir avec affolement : la nuit, toutes les expositions prennent vie ! Sous ses yeux, les soldats romains et les cow-boys miniatures se lancent dans une guerre acharnée, Attila et ses Huns commencent à piller les expositions avoisinantes, la momie tente de sortir de son sarcophage, le squelette du redoutable – mais néanmoins attachant – tyrannosaure rôde dans les couloirs... Le chaos est total ! Larry pourra-t-il remettre de l\'ordre dans ses collections et sauver le musée ?'),
(14, 'La Dolce Vita', 'https://image.tmdb.org/t/p/w640/l1QsL7eReqUhwc2iBG8jZ24IcRp.jpg', 'Le chroniqueur Marcello fait le tour des lieux à scandale de Rome pour alimenter les potins d\'un journal à fort tirage. Il rencontre une faune corrompue et dérisoire qui feint de s\'amuser et dissimule mal son ennui.'),
(15, 'Ocean s Eleven', 'https://image.tmdb.org/t/p/w640/xATFBKVVRKljvIN9XM1JFMFKCr1.jpg', 'Après deux ans passés dans la prison du New Jersey, Danny Ocean retrouve la liberté et s\'apprête à monter un coup qui semble impossible à réaliser : cambrioler dans le même temps les casinos Bellagio, Mirage et MGM Grand, avec une jolie somme de 150 millions de dollars à la clé. Il souhaite également récupérer Tess, sa bien-aimée que lui a volée Terry Benedict, le propriétaire de ces trois somptueux établissements de jeux de Las Vegas. Pour ce faire, Danny et son ami Rusty Ryan composent une équipe de dix malfrats maîtres dans leur spécialité. Parmi eux figurent Linus Caldwell, le pickpocket le plus agile qui soit ; Roscoe Means, un expert en explosifs ; Ruben Tishkoff, qui connaît les systèmes de sécurité des casinos sur le bout des doigts ; les frères Virgil et Turk Malloy, capables de revêtir plusieurs identités ; ou encore Yen, véritable contorsionniste et acrobate.'),
(16, 'Astérix et Obélix : Mission Cléopâtre', 'https://image.tmdb.org/t/p/w640/HkqnxgSH5yFFgY87nPj6bgKIP8.jpg', 'Cléopâtre, la reine d’Égypte, décide, pour défier l\'Empereur romain Jules César, de construire en trois mois un palais somptueux en plein désert. Si elle y parvient, celui-ci devra concéder publiquement que le peuple égyptien est le plus grand de tous les peuples. Pour ce faire, Cléopâtre fait appel à Numérobis, un architecte d\'avant-garde plein d\'énergie. S\'il réussit, elle le couvrira d\'or. S\'il échoue, elle le jettera aux crocodiles. Celui-ci, conscient du défi à relever, cherche de l\'aide auprès de son vieil ami Panoramix. Le druide fait le voyage en Égypte avec Astérix et Obélix. De son côté, Amonbofis, l\'architecte officiel de Cléopâtre, jaloux que la reine ait choisi Numérobis pour construire le palais, va tout mettre en œuvre pour faire échouer son concurrent.'),
(17, 'Blanche-neige et le chasseur', 'https://image.tmdb.org/t/p/w640/4LQ14eMtyRTN6fJK7cEa5pkop9d.jpg', 'Dans une réécriture du conte des frères Grimm, le chasseur supposé tuer Blanche-Neige dans les bois devient son protecteur et son mentor afin de vaincre la Reine maléfique.'),
(18, 'Le fabuleux destin d Amélie Poulain', 'https://image.tmdb.org/t/p/w640/8OCSJ1ggbLocG9kxIrQhhb81kOS.jpg', 'Amélie, une jeune serveuse dans un bar de Montmartre, passe son temps à observer les gens et à laisser son imagination divaguer. Elle s\'est fixé un but : faire le bien de ceux qui l\'entourent. Elle invente alors des stratagèmes pour intervenir incognito dans leur existence.Le chemin d\'Amélie est jalonné de rencontres : Georgette, la buraliste hypocondriaque ; Lucien, le commis d\'épicerie ; Madeleine Wallace, la concierge portée sur le porto et les chiens empaillés ; Raymond Dufayel alias "l\'homme de verre", son voisin qui ne vit qu\'à travers une reproduction d\'un tableau de Renoir.Cette quête du bonheur amène Amélie à faire la connaissance de Nino Quincampoix, un étrange "prince charmant". Celui-ci partage son temps entre un train fantôme et un sex-shop, et cherche à identifier un inconnu dont la photo réapparaît sans cesse dans plusieurs cabines de Photomaton.'),
(19, 'Le seigneur des anneaux', 'https://image.tmdb.org/t/p/original//yIQpDcczZJuj5tp60mWZnEGqhyg.jpg', 'Le jeune et timide Hobbit, Frodon Sacquet, hérite d\'un anneau. Bien loin d\'être une simple babiole, il s\'agit de l\'Anneau Unique, un instrument de pouvoir absolu qui permettrait à Sauron, le Seigneur des ténèbres, de régner sur la Terre du Milieu et de réduire en esclavage ses peuples. À moins que Frodon, aidé d\'une Compagnie constituée de Hobbits, d\'Hommes, d\'un Magicien, d\'un Nain, et d\'un Elfe, ne parvienne à emporter l\'Anneau à travers la Terre du Milieu jusqu\'à la Crevasse du Destin, lieu où il a été forgé, et à le détruire pour toujours. Un tel périple signifie s\'aventurer très loin en Mordor, les terres du Seigneur des ténèbres, où est rassemblée son armée d\'Orques maléfiques... La Compagnie doit non seulement combattre les forces extérieures du mal mais aussi les dissensions internes et l\'influence corruptrice qu\'exerce l\'Anneau lui-même.'),
(20, 'Harry Potter', 'https://image.tmdb.org/t/p/w640/4bUd3nUGD2XnhLkYNCXHFjPHEH5.jpg', 'Harry Potter, un jeune orphelin, est élevé par son oncle Vernon et sa tante Pétunia qui le détestent. Alors qu\'il était haut comme trois pommes, ces derniers lui ont raconté que ses parents étaient morts dans un accident de voiture. Le jour de son onzième anniversaire, Harry reçoit la visite inattendue d\'un homme gigantesque se nommant Rubeus Hagrid. Celui-ci lui révèle qu\'il est en fait le fils de deux puissants magiciens et qu\'il possède lui aussi d\'extraordinaires pouvoirs. C\'est avec joie que le garçon accepte de suivre des cours à Poudlard, la célèbre école de sorcellerie. Il a enfin la chance de se faire des amis. Blâmé par le professeur Severus Rogue qui lui enseigne les potions et protégé par Albus Dumbledore, le directeur de l\'établissement, Harry va tenter d\'élucider le mystère de la pierre philosophale..'),
(21, 'Jurassic Park', 'https://image.tmdb.org/t/p/w640/dDuKqYOlpXqYEDv9ffCypXfOHCI.jpg', 'Ne pas réveiller le chat qui dort... C\'est ce que le milliardaire John Hammond aurait dû se rappeler avant de se lancer dans le "clonage" de dinosaures. C\'est à partir d\'une goutte de sang absorbée par un moustique fossilisé que John Hammond et son équipe ont réussi à faire renaître une dizaine d\'espèces de dinosaures. Il s\'apprête maintenant avec la complicité du docteur Alan Grant, paléontologue de renom, et de son amie Ellie, à ouvrir le plus grand parc à thème du monde. Mais c\'était sans compter la cupidité et la malveillance de l\'informaticien Dennis Nedry, et éventuellement des dinosaures, seuls maîtres sur l\'île...'),
(22, 'Coup de foudre à Notting Hill', 'https://image.tmdb.org/t/p/w640/zZy1PNidUq5KVEPLoXo5eXDZJud.jpg', 'Quand un matin, Anna Scott, l\'actrice la plus célèbre d\'Hollywood, pousse la porte de la librairie de William Thacket, située dans le charmant quartier de Notting Hill, à l\'ouest de Londres, le libraire ignore que commence une grande aventure. Par une série de hasards comme seul le destin peut en mettre en scène, William et Anna vivent une rencontre étonnante, attachante. Lorsque la star le rappelle quelque temps plus tard, William n\'ose y croire.'),
(23, 'Rencontres du troisième type', 'https://image.tmdb.org/t/p/w1280/7JEJwW3LMaOsmZT2A3DGxQsuP7F.jpg', 'Des faits étranges se produisent un peu partout dans le monde : des avions qui avaient disparu durant la Seconde Guerre mondiale sont retrouvés au Mexique en parfait état de marche, un cargo est découvert échoué au beau milieu du désert de Gobi. Dans l\'Indiana, pendant qu\'une coupure d\'électricité paralyse la banlieue, Roy Neary, un réparateur de câbles, voit une "soucoupe volante" passer au-dessus de sa voiture. D\'autres personnes sont également témoins de ce type de phénomène : Barry Guiler, un petit garçon de quatre ans, est réveillé par le bruit de ses jouets qui se mettent en route. Cherchant à savoir d\'où proviennent ces ovnis, Roy Neary se heurte aux rigoureuses consignes de silence imposées par le gouvernement fédéral. Obsédé par ce qu\'il a vu et hanté par une image de montagne qu\'il essaie désespérément de reconstituer, il est abandonné par sa femme Ronnie et ses enfants. Il n\'y a que Jillian, la mère de Barry, qui le comprenne.'),
(24, 'Midnight in Paris', 'https://image.tmdb.org/t/p/w640/xxSopLYATHXSepXcEaBh9Gazv6p.jpg', 'Scénariste hollywoodien à succès, Gil vit dans la nostalgie du Paris des années 1920 et le souci du grand roman qu\'il ne cesse d\'écrire et de peaufiner. Il séjourne précisément à Paris avec Inez, la belle Américaine qu\'il doit épouser sous la menace permanente de ses beaux-parents, des ultra-conservateurs coincés, et d\'un vieil ami d\'université pédant et hautain. Un soir qu\'il tente d\'échapper à cette pesante atmosphère, sur les douze coups de minuit, une mystérieuse automobile le prend à son bord. Le voici propulsé dans les années 1920, avec Hemingway, le couple Fitzgerald, Picasso et la belle Adriana, la maîtresse du peintre espagnol...');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `movie`
--
ALTER TABLE `movie`
  ADD PRIMARY KEY (`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
